const $=s=>document.querySelector(s);
const fmt=n=>n==null?"–":new Intl.NumberFormat("de-DE").format(n);
const date=v=>v?new Date(v).toLocaleDateString("de-DE"):"–";
let D=null;
function latest(p){return p.snapshots?.at(-1)||{}}
function card(p){const m=p.membership||{},l=latest(p);return `<article class="player-card hof-card"><div class="player-meta"><span class="member-status ${p.is_active?'active':'former'}">${p.is_active?'Aktiv':'Ehemalig'}</span><a href="player.html?id=${p.id}">Historie →</a></div><h3>${p.name}</h3><div class="metric-row"><span>Beitritt erfasst</span><strong>${date(m.joined_at||p.first_seen)}</strong></div><div class="metric-row"><span>${p.is_active?'Mitglied seit':'Austritt erfasst'}</span><strong>${p.is_active?`${fmt(p.membership_days)} Tage`:date(m.left_at)}</strong></div><div class="metric-row"><span>Zeit in der Allianz</span><strong>${fmt(p.membership_days)} Tage</strong></div><div class="metric-row"><span>Letzte Gesamtpunkte</span><strong>${fmt(l.total_points)}</strong></div><div class="metric-row"><span>Letzter Rang</span><strong>${fmt(l.total_rank)}</strong></div><div class="metric-row"><span>Letzter Snapshot</span><strong>${l.date||'–'}</strong></div></article>`}
function render(){const q=$("#hofSearch").value.trim().toLowerCase(),all=D.players.filter(p=>p.name.toLowerCase().includes(q)),active=all.filter(p=>p.is_active),former=all.filter(p=>!p.is_active);$("#activeMembers").innerHTML=active.map(card).join('')||'<p class="muted">Keine aktiven Mitglieder gefunden.</p>';$("#formerMembers").innerHTML=former.map(card).join('')||'<p class="muted">Noch keine ehemaligen Mitglieder erfasst.</p>';$("#hofSummary").innerHTML=`<article class="summary-card"><span class="summary-label">Aktiv</span><strong class="summary-value">${active.length}</strong></article><article class="summary-card"><span class="summary-label">Ehemalig</span><strong class="summary-value">${former.length}</strong></article><article class="summary-card"><span class="summary-label">Gesamt erfasst</span><strong class="summary-value">${all.length}</strong></article>`}
fetch('data.json',{cache:'no-store'}).then(r=>r.json()).then(j=>{D=j;$("#subtitle").textContent=`${D.alliance?.tag?`[${D.alliance.tag}] · `:''}Aktive und bisherige Mitglieder`;$("#footer").textContent=`Erzeugt ${new Date(D.meta.generated_at).toLocaleString('de-DE')}`;render()}).catch(e=>$("#subtitle").textContent=`Fehler: ${e.message}`);
$("#hofSearch").addEventListener('input',render);
