const state={summary:null,snapshots:[],planets:[],production:[],technologies:[],flights:[],selectedAccount:null};
const $=s=>document.querySelector(s);const nf=new Intl.NumberFormat('de-DE');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=v=>Number.isFinite(Number(v))?nf.format(Math.trunc(Number(v))):'–';
const prodFmt=v=>{v=Number(v)||0;if(Math.abs(v)<1000)return fmt(v);if(Math.abs(v)<1e6)return `${Math.floor(v/100)/10} K`;return `${Math.floor(v/1e6)} M`};
const dateFmt=v=>v?new Date(v).toLocaleString('de-DE'):'–';
async function json(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);return r.json()}
function accountKey(a){return `${a.player_id}|${a.universe}`}
function account(){return state.summary.accounts.find(a=>accountKey(a)===state.selectedAccount)}
function latest(a){return state.snapshots.filter(s=>s.player_id===a.player_id&&s.universe===a.universe).sort((x,y)=>y.created_at.localeCompare(x.created_at))[0]}
function ownRows(list,s){return list.filter(x=>x.snapshot_id===s.snapshot_id)}
function sumShipsMap(flights){const out={};for(const f of flights){for(const [key,val] of Object.entries(f.ships||{}))out[key]=(out[key]||0)+(Number(val)||0)}return out}
function movingShipTotal(flights){return flights.reduce((sum,f)=>{const explicit=Number(f.ship_count);if(Number.isFinite(explicit)&&explicit>=0)return sum+explicit;return sum+Object.values(f.ships||{}).reduce((n,v)=>n+(Number(v)||0),0)},0)}
function shipValue(map,name,id){return Number(map[name]??map[id]??map[String(id)]??0)||0}
function setColumnWidth(count){const usable=Math.max(760,window.innerWidth)-430;const width=Math.max(82,Math.min(122,Math.floor(usable/Math.max(count,1))));document.documentElement.style.setProperty('--planet-width',`${width}px`)}
function header(planets){return `<tr><th class="label-col">Imperium</th>${planets.map(p=>`<th class="planet-head">${p.image_url?`<img class="planet-image" src="${esc(p.image_url)}" alt="">`:`<div class="planet-image"></div>`}<div class="planet-name">${esc(p.name)}</div><div class="coords">${esc(p.coordinates)}</div><div class="planet-meta">${fmt(p.fields_used)}/${fmt(p.fields_total)} · ${fmt(p.temperature_min_c)}–${fmt(p.temperature_max_c)} °C</div></th>`).join('')}<th class="summary-col">Ø</th><th class="travelling-col">Unterwegs</th><th class="summary-col">Gesamt</th></tr>`}
function section(title,key,rows,subtitle=''){if(!rows)return '';return `<tr class="section-row" data-section="${key}"><td colspan="999"><button class="section-button" data-toggle="${key}"><span>${esc(title)}</span>${subtitle?`<small>${esc(subtitle)}</small>`:''}</button></td></tr>${rows}`}
function productionRows(planets,prods){const defs=[['Metall / h','metal_per_hour','metal'],['Kristall / h','crystal_per_hour','crystal'],['Deuterium / h','deuterium_per_hour','deut'],['Energie','energy_available','energy']];return defs.map(([label,key,cls])=>{const vals=planets.map(p=>Number(prods.get(p.planet_id)?.[key]||0));const total=vals.reduce((a,b)=>a+b,0),avg=vals.length?total/vals.length:0;return `<tr class="data-row production-row ${cls}" data-group="production"><td class="label-col">${label}</td>${vals.map(v=>`<td>${prodFmt(v)}</td>`).join('')}<td class="summary-col">${prodFmt(avg)}</td><td class="travelling-col">–</td><td class="summary-col">${prodFmt(total)}</td></tr>`}).join('')}
function technologyDefs(category,techRows){const defs=[];const seen=new Set();for(const t of techRows.filter(t=>t.category===category)){const k=String(t.technology_id);if(!seen.has(k)){seen.add(k);defs.push({id:k,name:t.name})}}return defs.sort((a,b)=>(Number(a.id)||999999)-(Number(b.id)||999999))}
function technologyRows(category,planets,techRows,travelling){const rows=techRows.filter(t=>t.category===category);const defs=technologyDefs(category,techRows);if(!defs.length)return '';
 const byPlanet=new Map(planets.map(p=>[p.planet_id,new Map()]));const accountValues=new Map();
 for(const t of rows){if(t.planet_id==null){const old=accountValues.get(String(t.technology_id));if(!old||Number(t.value)>Number(old.value))accountValues.set(String(t.technology_id),t)}else byPlanet.get(t.planet_id)?.set(String(t.technology_id),t)}
 return defs.map(d=>{const accountValue=Number(accountValues.get(d.id)?.value||0);const vals=planets.map(p=>{const own=byPlanet.get(p.planet_id)?.get(d.id);return own?Number(own.value||0):(category==='research'&&accountValue?accountValue:0)});const max=Math.max(...vals,accountValue,0),sum=vals.reduce((a,b)=>a+b,0),avg=vals.length?sum/vals.length:0;const moving=category==='ships'?shipValue(travelling,d.name,d.id):0;const total=category==='research'?(accountValue||max):sum+moving;return `<tr class="data-row" data-group="${category}"><td class="label-col"><span class="tech-label">${esc(d.name)}</span></td>${vals.map(v=>`<td class="${v===0?'zero ':''}${v===max&&max>0?'high':''}">${fmt(v)}</td>`).join('')}<td class="summary-col">${category==='ships'||category==='defenses'?fmt(avg):avg.toLocaleString('de-DE',{maximumFractionDigits:1})}</td><td class="travelling-col ${moving?'high':'zero'}">${category==='ships'?(moving?fmt(moving):'–'):'–'}</td><td class="summary-col">${fmt(total)}</td></tr>`}).join('')}
function lifeformSubtitle(planets){const names=[...new Set(planets.map(p=>p.lifeform_name).filter(Boolean))];return names.length?names.join(' · '):''}
function render(){const a=account(),s=a&&latest(a);if(!s)return;const planets=ownRows(state.planets,s).sort((x,y)=>(x.planet_order??999)-(y.planet_order??999));setColumnWidth(planets.length);const prodRows=ownRows(state.production,s),techRows=ownRows(state.technologies,s),flights=ownRows(state.flights,s);const prods=new Map(prodRows.map(x=>[x.planet_id,x]));const travelling=sumShipsMap(flights);const stationary=techRows.filter(t=>t.category==='ships').reduce((n,t)=>n+(Number(t.value)||0),0);const moving=movingShipTotal(flights);const totals={metal:0,crystal:0,deut:0};for(const p of planets){const r=prods.get(p.planet_id)||{};totals.metal+=Number(r.metal_per_hour)||0;totals.crystal+=Number(r.crystal_per_hour)||0;totals.deut+=Number(r.deuterium_per_hour)||0}
 $('#playerName').textContent=a.player_name;$('#universe').textContent=a.universe;$('#latestSnapshot').textContent=dateFmt(s.created_at);$('#planetCount').textContent=fmt(planets.length);$('#totalMetal').textContent=prodFmt(totals.metal);$('#totalCrystal').textContent=prodFmt(totals.crystal);$('#totalDeuterium').textContent=prodFmt(totals.deut);$('#stationedShips').textContent=fmt(stationary);$('#travellingShips').textContent=fmt(moving);$('#allShips').textContent=fmt(stationary+moving);$('#travellingHint').textContent=moving===0&&flights.length?'Flotten erkannt, aber Anzahl nicht lesbar':'';$('#empireHead').innerHTML=header(planets);
 const categories=[['Gebäude','buildings'],['Anlagen','facilities'],['Forschung','research'],['Schiffe','ships'],['Verteidigung','defenses']];let body=section('Produktion','production',productionRows(planets,prods));for(const [label,key] of categories)body+=section(label,key,technologyRows(key,planets,techRows,travelling));const lfBuildings=technologyRows('lifeform_buildings',planets,techRows,travelling);const lfResearch=technologyRows('lifeform_research',planets,techRows,travelling);body+=section('Lebensformen · Gebäude','lifeform_buildings',lfBuildings,lifeformSubtitle(planets));body+=section('Lebensformen · Forschung','lifeform_research',lfResearch,lifeformSubtitle(planets));$('#empireBody').innerHTML=body;
 document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const key=b.dataset.toggle;b.closest('.section-row').classList.toggle('collapsed');document.querySelectorAll(`[data-group="${key}"]`).forEach(r=>r.classList.toggle('hidden-row'))})}
async function init(){try{const [summary,snapshots,planets,production,technologies,flights]=await Promise.all(['summary','snapshots','planets','production','technologies','active_flights'].map(n=>json(`data/${n}.json`)));Object.assign(state,{summary,snapshots,planets,production,technologies,flights});const sel=$('#accountSelect');sel.innerHTML=summary.accounts.map(a=>`<option value="${esc(accountKey(a))}">${esc(a.player_name)} · ${esc(a.universe)}</option>`).join('');state.selectedAccount=sel.value;sel.onchange=()=>{state.selectedAccount=sel.value;render()};$('#reloadButton').onclick=()=>location.reload();window.addEventListener('resize',()=>setColumnWidth(ownRows(state.planets,latest(account())).length));render()}catch(e){$('#message').textContent=`Dashboard konnte nicht geladen werden: ${e.message}`;$('#message').classList.remove('hidden')}}init();
